/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RaftRPC_H
#define RaftRPC_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "raft_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class RaftRPCIf {
 public:
  virtual ~RaftRPCIf() {}
  virtual void requestVote(RequestVoteResult& _return, const RequestVoteParams& params) = 0;
  virtual void appendEntries(AppendEntriesResult& _return, const AppendEntriesParams& params) = 0;
  virtual void getState(RaftState& _return) = 0;
  virtual void start(StartResult& _return, const std::string& command) = 0;
};

class RaftRPCIfFactory {
 public:
  typedef RaftRPCIf Handler;

  virtual ~RaftRPCIfFactory() {}

  virtual RaftRPCIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(RaftRPCIf* /* handler */) = 0;
  };

class RaftRPCIfSingletonFactory : virtual public RaftRPCIfFactory {
 public:
  RaftRPCIfSingletonFactory(const ::std::shared_ptr<RaftRPCIf>& iface) : iface_(iface) {}
  virtual ~RaftRPCIfSingletonFactory() {}

  virtual RaftRPCIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(RaftRPCIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<RaftRPCIf> iface_;
};

class RaftRPCNull : virtual public RaftRPCIf {
 public:
  virtual ~RaftRPCNull() {}
  void requestVote(RequestVoteResult& /* _return */, const RequestVoteParams& /* params */) override {
    return;
  }
  void appendEntries(AppendEntriesResult& /* _return */, const AppendEntriesParams& /* params */) override {
    return;
  }
  void getState(RaftState& /* _return */) override {
    return;
  }
  void start(StartResult& /* _return */, const std::string& /* command */) override {
    return;
  }
};

typedef struct _RaftRPC_requestVote_args__isset {
  _RaftRPC_requestVote_args__isset() : params(false) {}
  bool params :1;
} _RaftRPC_requestVote_args__isset;

class RaftRPC_requestVote_args {
 public:

  RaftRPC_requestVote_args(const RaftRPC_requestVote_args&);
  RaftRPC_requestVote_args& operator=(const RaftRPC_requestVote_args&);
  RaftRPC_requestVote_args() noexcept {
  }

  virtual ~RaftRPC_requestVote_args() noexcept;
  RequestVoteParams params;

  _RaftRPC_requestVote_args__isset __isset;

  void __set_params(const RequestVoteParams& val);

  bool operator == (const RaftRPC_requestVote_args & rhs) const
  {
    if (!(params == rhs.params))
      return false;
    return true;
  }
  bool operator != (const RaftRPC_requestVote_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftRPC_requestVote_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RaftRPC_requestVote_pargs {
 public:


  virtual ~RaftRPC_requestVote_pargs() noexcept;
  const RequestVoteParams* params;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftRPC_requestVote_result__isset {
  _RaftRPC_requestVote_result__isset() : success(false) {}
  bool success :1;
} _RaftRPC_requestVote_result__isset;

class RaftRPC_requestVote_result {
 public:

  RaftRPC_requestVote_result(const RaftRPC_requestVote_result&) noexcept;
  RaftRPC_requestVote_result& operator=(const RaftRPC_requestVote_result&) noexcept;
  RaftRPC_requestVote_result() noexcept {
  }

  virtual ~RaftRPC_requestVote_result() noexcept;
  RequestVoteResult success;

  _RaftRPC_requestVote_result__isset __isset;

  void __set_success(const RequestVoteResult& val);

  bool operator == (const RaftRPC_requestVote_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RaftRPC_requestVote_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftRPC_requestVote_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftRPC_requestVote_presult__isset {
  _RaftRPC_requestVote_presult__isset() : success(false) {}
  bool success :1;
} _RaftRPC_requestVote_presult__isset;

class RaftRPC_requestVote_presult {
 public:


  virtual ~RaftRPC_requestVote_presult() noexcept;
  RequestVoteResult* success;

  _RaftRPC_requestVote_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RaftRPC_appendEntries_args__isset {
  _RaftRPC_appendEntries_args__isset() : params(false) {}
  bool params :1;
} _RaftRPC_appendEntries_args__isset;

class RaftRPC_appendEntries_args {
 public:

  RaftRPC_appendEntries_args(const RaftRPC_appendEntries_args&);
  RaftRPC_appendEntries_args& operator=(const RaftRPC_appendEntries_args&);
  RaftRPC_appendEntries_args() noexcept {
  }

  virtual ~RaftRPC_appendEntries_args() noexcept;
  AppendEntriesParams params;

  _RaftRPC_appendEntries_args__isset __isset;

  void __set_params(const AppendEntriesParams& val);

  bool operator == (const RaftRPC_appendEntries_args & rhs) const
  {
    if (!(params == rhs.params))
      return false;
    return true;
  }
  bool operator != (const RaftRPC_appendEntries_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftRPC_appendEntries_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RaftRPC_appendEntries_pargs {
 public:


  virtual ~RaftRPC_appendEntries_pargs() noexcept;
  const AppendEntriesParams* params;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftRPC_appendEntries_result__isset {
  _RaftRPC_appendEntries_result__isset() : success(false) {}
  bool success :1;
} _RaftRPC_appendEntries_result__isset;

class RaftRPC_appendEntries_result {
 public:

  RaftRPC_appendEntries_result(const RaftRPC_appendEntries_result&) noexcept;
  RaftRPC_appendEntries_result& operator=(const RaftRPC_appendEntries_result&) noexcept;
  RaftRPC_appendEntries_result() noexcept {
  }

  virtual ~RaftRPC_appendEntries_result() noexcept;
  AppendEntriesResult success;

  _RaftRPC_appendEntries_result__isset __isset;

  void __set_success(const AppendEntriesResult& val);

  bool operator == (const RaftRPC_appendEntries_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RaftRPC_appendEntries_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftRPC_appendEntries_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftRPC_appendEntries_presult__isset {
  _RaftRPC_appendEntries_presult__isset() : success(false) {}
  bool success :1;
} _RaftRPC_appendEntries_presult__isset;

class RaftRPC_appendEntries_presult {
 public:


  virtual ~RaftRPC_appendEntries_presult() noexcept;
  AppendEntriesResult* success;

  _RaftRPC_appendEntries_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class RaftRPC_getState_args {
 public:

  RaftRPC_getState_args(const RaftRPC_getState_args&) noexcept;
  RaftRPC_getState_args& operator=(const RaftRPC_getState_args&) noexcept;
  RaftRPC_getState_args() noexcept {
  }

  virtual ~RaftRPC_getState_args() noexcept;

  bool operator == (const RaftRPC_getState_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const RaftRPC_getState_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftRPC_getState_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RaftRPC_getState_pargs {
 public:


  virtual ~RaftRPC_getState_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftRPC_getState_result__isset {
  _RaftRPC_getState_result__isset() : success(false) {}
  bool success :1;
} _RaftRPC_getState_result__isset;

class RaftRPC_getState_result {
 public:

  RaftRPC_getState_result(const RaftRPC_getState_result&);
  RaftRPC_getState_result& operator=(const RaftRPC_getState_result&);
  RaftRPC_getState_result() noexcept {
  }

  virtual ~RaftRPC_getState_result() noexcept;
  RaftState success;

  _RaftRPC_getState_result__isset __isset;

  void __set_success(const RaftState& val);

  bool operator == (const RaftRPC_getState_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RaftRPC_getState_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftRPC_getState_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftRPC_getState_presult__isset {
  _RaftRPC_getState_presult__isset() : success(false) {}
  bool success :1;
} _RaftRPC_getState_presult__isset;

class RaftRPC_getState_presult {
 public:


  virtual ~RaftRPC_getState_presult() noexcept;
  RaftState* success;

  _RaftRPC_getState_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RaftRPC_start_args__isset {
  _RaftRPC_start_args__isset() : command(false) {}
  bool command :1;
} _RaftRPC_start_args__isset;

class RaftRPC_start_args {
 public:

  RaftRPC_start_args(const RaftRPC_start_args&);
  RaftRPC_start_args& operator=(const RaftRPC_start_args&);
  RaftRPC_start_args() noexcept
                     : command() {
  }

  virtual ~RaftRPC_start_args() noexcept;
  std::string command;

  _RaftRPC_start_args__isset __isset;

  void __set_command(const std::string& val);

  bool operator == (const RaftRPC_start_args & rhs) const
  {
    if (!(command == rhs.command))
      return false;
    return true;
  }
  bool operator != (const RaftRPC_start_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftRPC_start_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RaftRPC_start_pargs {
 public:


  virtual ~RaftRPC_start_pargs() noexcept;
  const std::string* command;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftRPC_start_result__isset {
  _RaftRPC_start_result__isset() : success(false) {}
  bool success :1;
} _RaftRPC_start_result__isset;

class RaftRPC_start_result {
 public:

  RaftRPC_start_result(const RaftRPC_start_result&) noexcept;
  RaftRPC_start_result& operator=(const RaftRPC_start_result&) noexcept;
  RaftRPC_start_result() noexcept {
  }

  virtual ~RaftRPC_start_result() noexcept;
  StartResult success;

  _RaftRPC_start_result__isset __isset;

  void __set_success(const StartResult& val);

  bool operator == (const RaftRPC_start_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RaftRPC_start_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftRPC_start_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftRPC_start_presult__isset {
  _RaftRPC_start_presult__isset() : success(false) {}
  bool success :1;
} _RaftRPC_start_presult__isset;

class RaftRPC_start_presult {
 public:


  virtual ~RaftRPC_start_presult() noexcept;
  StartResult* success;

  _RaftRPC_start_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class RaftRPCClient : virtual public RaftRPCIf {
 public:
  RaftRPCClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  RaftRPCClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void requestVote(RequestVoteResult& _return, const RequestVoteParams& params) override;
  void send_requestVote(const RequestVoteParams& params);
  void recv_requestVote(RequestVoteResult& _return);
  void appendEntries(AppendEntriesResult& _return, const AppendEntriesParams& params) override;
  void send_appendEntries(const AppendEntriesParams& params);
  void recv_appendEntries(AppendEntriesResult& _return);
  void getState(RaftState& _return) override;
  void send_getState();
  void recv_getState(RaftState& _return);
  void start(StartResult& _return, const std::string& command) override;
  void send_start(const std::string& command);
  void recv_start(StartResult& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class RaftRPCProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<RaftRPCIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (RaftRPCProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_requestVote(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_appendEntries(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getState(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_start(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  RaftRPCProcessor(::std::shared_ptr<RaftRPCIf> iface) :
    iface_(iface) {
    processMap_["requestVote"] = &RaftRPCProcessor::process_requestVote;
    processMap_["appendEntries"] = &RaftRPCProcessor::process_appendEntries;
    processMap_["getState"] = &RaftRPCProcessor::process_getState;
    processMap_["start"] = &RaftRPCProcessor::process_start;
  }

  virtual ~RaftRPCProcessor() {}
};

class RaftRPCProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  RaftRPCProcessorFactory(const ::std::shared_ptr< RaftRPCIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< RaftRPCIfFactory > handlerFactory_;
};

class RaftRPCMultiface : virtual public RaftRPCIf {
 public:
  RaftRPCMultiface(std::vector<std::shared_ptr<RaftRPCIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~RaftRPCMultiface() {}
 protected:
  std::vector<std::shared_ptr<RaftRPCIf> > ifaces_;
  RaftRPCMultiface() {}
  void add(::std::shared_ptr<RaftRPCIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void requestVote(RequestVoteResult& _return, const RequestVoteParams& params) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->requestVote(_return, params);
    }
    ifaces_[i]->requestVote(_return, params);
    return;
  }

  void appendEntries(AppendEntriesResult& _return, const AppendEntriesParams& params) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->appendEntries(_return, params);
    }
    ifaces_[i]->appendEntries(_return, params);
    return;
  }

  void getState(RaftState& _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getState(_return);
    }
    ifaces_[i]->getState(_return);
    return;
  }

  void start(StartResult& _return, const std::string& command) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->start(_return, command);
    }
    ifaces_[i]->start(_return, command);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class RaftRPCConcurrentClient : virtual public RaftRPCIf {
 public:
  RaftRPCConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  RaftRPCConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void requestVote(RequestVoteResult& _return, const RequestVoteParams& params) override;
  int32_t send_requestVote(const RequestVoteParams& params);
  void recv_requestVote(RequestVoteResult& _return, const int32_t seqid);
  void appendEntries(AppendEntriesResult& _return, const AppendEntriesParams& params) override;
  int32_t send_appendEntries(const AppendEntriesParams& params);
  void recv_appendEntries(AppendEntriesResult& _return, const int32_t seqid);
  void getState(RaftState& _return) override;
  int32_t send_getState();
  void recv_getState(RaftState& _return, const int32_t seqid);
  void start(StartResult& _return, const std::string& command) override;
  int32_t send_start(const std::string& command);
  void recv_start(StartResult& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
