/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Shardctrler_H
#define Shardctrler_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "KVRaft_types.h"
#include "Raft.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ShardctrlerIf : virtual public RaftIf {
 public:
  virtual ~ShardctrlerIf() {}
  virtual void join(JoinReply& _return, const JoinArgs& jargs) = 0;
  virtual void leave(LeaveReply& _return, const LeaveArgs& largs) = 0;
  virtual void move(MoveReply& _return, const MoveArgs& margs) = 0;
  virtual void query(QueryReply& _return, const QueryArgs& qargs) = 0;
};

class ShardctrlerIfFactory : virtual public RaftIfFactory {
 public:
  typedef ShardctrlerIf Handler;

  virtual ~ShardctrlerIfFactory() {}

  virtual ShardctrlerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) override = 0;
  virtual void releaseHandler(RaftIf* /* handler */) override = 0;
  };

class ShardctrlerIfSingletonFactory : virtual public ShardctrlerIfFactory {
 public:
  ShardctrlerIfSingletonFactory(const ::std::shared_ptr<ShardctrlerIf>& iface) : iface_(iface) {}
  virtual ~ShardctrlerIfSingletonFactory() {}

  virtual ShardctrlerIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(RaftIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<ShardctrlerIf> iface_;
};

class ShardctrlerNull : virtual public ShardctrlerIf , virtual public RaftNull {
 public:
  virtual ~ShardctrlerNull() {}
  void join(JoinReply& /* _return */, const JoinArgs& /* jargs */) override {
    return;
  }
  void leave(LeaveReply& /* _return */, const LeaveArgs& /* largs */) override {
    return;
  }
  void move(MoveReply& /* _return */, const MoveArgs& /* margs */) override {
    return;
  }
  void query(QueryReply& /* _return */, const QueryArgs& /* qargs */) override {
    return;
  }
};

typedef struct _Shardctrler_join_args__isset {
  _Shardctrler_join_args__isset() : jargs(false) {}
  bool jargs :1;
} _Shardctrler_join_args__isset;

class Shardctrler_join_args {
 public:

  Shardctrler_join_args(const Shardctrler_join_args&);
  Shardctrler_join_args& operator=(const Shardctrler_join_args&);
  Shardctrler_join_args() noexcept {
  }

  virtual ~Shardctrler_join_args() noexcept;
  JoinArgs jargs;

  _Shardctrler_join_args__isset __isset;

  void __set_jargs(const JoinArgs& val);

  bool operator == (const Shardctrler_join_args & rhs) const
  {
    if (!(jargs == rhs.jargs))
      return false;
    return true;
  }
  bool operator != (const Shardctrler_join_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Shardctrler_join_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Shardctrler_join_pargs {
 public:


  virtual ~Shardctrler_join_pargs() noexcept;
  const JoinArgs* jargs;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Shardctrler_join_result__isset {
  _Shardctrler_join_result__isset() : success(false) {}
  bool success :1;
} _Shardctrler_join_result__isset;

class Shardctrler_join_result {
 public:

  Shardctrler_join_result(const Shardctrler_join_result&) noexcept;
  Shardctrler_join_result& operator=(const Shardctrler_join_result&) noexcept;
  Shardctrler_join_result() noexcept {
  }

  virtual ~Shardctrler_join_result() noexcept;
  JoinReply success;

  _Shardctrler_join_result__isset __isset;

  void __set_success(const JoinReply& val);

  bool operator == (const Shardctrler_join_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Shardctrler_join_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Shardctrler_join_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Shardctrler_join_presult__isset {
  _Shardctrler_join_presult__isset() : success(false) {}
  bool success :1;
} _Shardctrler_join_presult__isset;

class Shardctrler_join_presult {
 public:


  virtual ~Shardctrler_join_presult() noexcept;
  JoinReply* success;

  _Shardctrler_join_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Shardctrler_leave_args__isset {
  _Shardctrler_leave_args__isset() : largs(false) {}
  bool largs :1;
} _Shardctrler_leave_args__isset;

class Shardctrler_leave_args {
 public:

  Shardctrler_leave_args(const Shardctrler_leave_args&);
  Shardctrler_leave_args& operator=(const Shardctrler_leave_args&);
  Shardctrler_leave_args() noexcept {
  }

  virtual ~Shardctrler_leave_args() noexcept;
  LeaveArgs largs;

  _Shardctrler_leave_args__isset __isset;

  void __set_largs(const LeaveArgs& val);

  bool operator == (const Shardctrler_leave_args & rhs) const
  {
    if (!(largs == rhs.largs))
      return false;
    return true;
  }
  bool operator != (const Shardctrler_leave_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Shardctrler_leave_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Shardctrler_leave_pargs {
 public:


  virtual ~Shardctrler_leave_pargs() noexcept;
  const LeaveArgs* largs;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Shardctrler_leave_result__isset {
  _Shardctrler_leave_result__isset() : success(false) {}
  bool success :1;
} _Shardctrler_leave_result__isset;

class Shardctrler_leave_result {
 public:

  Shardctrler_leave_result(const Shardctrler_leave_result&) noexcept;
  Shardctrler_leave_result& operator=(const Shardctrler_leave_result&) noexcept;
  Shardctrler_leave_result() noexcept {
  }

  virtual ~Shardctrler_leave_result() noexcept;
  LeaveReply success;

  _Shardctrler_leave_result__isset __isset;

  void __set_success(const LeaveReply& val);

  bool operator == (const Shardctrler_leave_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Shardctrler_leave_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Shardctrler_leave_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Shardctrler_leave_presult__isset {
  _Shardctrler_leave_presult__isset() : success(false) {}
  bool success :1;
} _Shardctrler_leave_presult__isset;

class Shardctrler_leave_presult {
 public:


  virtual ~Shardctrler_leave_presult() noexcept;
  LeaveReply* success;

  _Shardctrler_leave_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Shardctrler_move_args__isset {
  _Shardctrler_move_args__isset() : margs(false) {}
  bool margs :1;
} _Shardctrler_move_args__isset;

class Shardctrler_move_args {
 public:

  Shardctrler_move_args(const Shardctrler_move_args&) noexcept;
  Shardctrler_move_args& operator=(const Shardctrler_move_args&) noexcept;
  Shardctrler_move_args() noexcept {
  }

  virtual ~Shardctrler_move_args() noexcept;
  MoveArgs margs;

  _Shardctrler_move_args__isset __isset;

  void __set_margs(const MoveArgs& val);

  bool operator == (const Shardctrler_move_args & rhs) const
  {
    if (!(margs == rhs.margs))
      return false;
    return true;
  }
  bool operator != (const Shardctrler_move_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Shardctrler_move_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Shardctrler_move_pargs {
 public:


  virtual ~Shardctrler_move_pargs() noexcept;
  const MoveArgs* margs;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Shardctrler_move_result__isset {
  _Shardctrler_move_result__isset() : success(false) {}
  bool success :1;
} _Shardctrler_move_result__isset;

class Shardctrler_move_result {
 public:

  Shardctrler_move_result(const Shardctrler_move_result&) noexcept;
  Shardctrler_move_result& operator=(const Shardctrler_move_result&) noexcept;
  Shardctrler_move_result() noexcept {
  }

  virtual ~Shardctrler_move_result() noexcept;
  MoveReply success;

  _Shardctrler_move_result__isset __isset;

  void __set_success(const MoveReply& val);

  bool operator == (const Shardctrler_move_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Shardctrler_move_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Shardctrler_move_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Shardctrler_move_presult__isset {
  _Shardctrler_move_presult__isset() : success(false) {}
  bool success :1;
} _Shardctrler_move_presult__isset;

class Shardctrler_move_presult {
 public:


  virtual ~Shardctrler_move_presult() noexcept;
  MoveReply* success;

  _Shardctrler_move_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Shardctrler_query_args__isset {
  _Shardctrler_query_args__isset() : qargs(false) {}
  bool qargs :1;
} _Shardctrler_query_args__isset;

class Shardctrler_query_args {
 public:

  Shardctrler_query_args(const Shardctrler_query_args&) noexcept;
  Shardctrler_query_args& operator=(const Shardctrler_query_args&) noexcept;
  Shardctrler_query_args() noexcept {
  }

  virtual ~Shardctrler_query_args() noexcept;
  QueryArgs qargs;

  _Shardctrler_query_args__isset __isset;

  void __set_qargs(const QueryArgs& val);

  bool operator == (const Shardctrler_query_args & rhs) const
  {
    if (!(qargs == rhs.qargs))
      return false;
    return true;
  }
  bool operator != (const Shardctrler_query_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Shardctrler_query_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Shardctrler_query_pargs {
 public:


  virtual ~Shardctrler_query_pargs() noexcept;
  const QueryArgs* qargs;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Shardctrler_query_result__isset {
  _Shardctrler_query_result__isset() : success(false) {}
  bool success :1;
} _Shardctrler_query_result__isset;

class Shardctrler_query_result {
 public:

  Shardctrler_query_result(const Shardctrler_query_result&);
  Shardctrler_query_result& operator=(const Shardctrler_query_result&);
  Shardctrler_query_result() noexcept {
  }

  virtual ~Shardctrler_query_result() noexcept;
  QueryReply success;

  _Shardctrler_query_result__isset __isset;

  void __set_success(const QueryReply& val);

  bool operator == (const Shardctrler_query_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Shardctrler_query_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Shardctrler_query_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Shardctrler_query_presult__isset {
  _Shardctrler_query_presult__isset() : success(false) {}
  bool success :1;
} _Shardctrler_query_presult__isset;

class Shardctrler_query_presult {
 public:


  virtual ~Shardctrler_query_presult() noexcept;
  QueryReply* success;

  _Shardctrler_query_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ShardctrlerClient : virtual public ShardctrlerIf, public RaftClient {
 public:
  ShardctrlerClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    RaftClient(prot, prot) {}
  ShardctrlerClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    RaftClient(iprot, oprot) {}
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void join(JoinReply& _return, const JoinArgs& jargs) override;
  void send_join(const JoinArgs& jargs);
  void recv_join(JoinReply& _return);
  void leave(LeaveReply& _return, const LeaveArgs& largs) override;
  void send_leave(const LeaveArgs& largs);
  void recv_leave(LeaveReply& _return);
  void move(MoveReply& _return, const MoveArgs& margs) override;
  void send_move(const MoveArgs& margs);
  void recv_move(MoveReply& _return);
  void query(QueryReply& _return, const QueryArgs& qargs) override;
  void send_query(const QueryArgs& qargs);
  void recv_query(QueryReply& _return);
};

class ShardctrlerProcessor : public RaftProcessor {
 protected:
  ::std::shared_ptr<ShardctrlerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (ShardctrlerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_join(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_leave(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_move(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_query(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ShardctrlerProcessor(::std::shared_ptr<ShardctrlerIf> iface) :
    RaftProcessor(iface),
    iface_(iface) {
    processMap_["join"] = &ShardctrlerProcessor::process_join;
    processMap_["leave"] = &ShardctrlerProcessor::process_leave;
    processMap_["move"] = &ShardctrlerProcessor::process_move;
    processMap_["query"] = &ShardctrlerProcessor::process_query;
  }

  virtual ~ShardctrlerProcessor() {}
};

class ShardctrlerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ShardctrlerProcessorFactory(const ::std::shared_ptr< ShardctrlerIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< ShardctrlerIfFactory > handlerFactory_;
};

class ShardctrlerMultiface : virtual public ShardctrlerIf, public RaftMultiface {
 public:
  ShardctrlerMultiface(std::vector<std::shared_ptr<ShardctrlerIf> >& ifaces) : ifaces_(ifaces) {
    std::vector<std::shared_ptr<ShardctrlerIf> >::iterator iter;
    for (iter = ifaces.begin(); iter != ifaces.end(); ++iter) {
      RaftMultiface::add(*iter);
    }
  }
  virtual ~ShardctrlerMultiface() {}
 protected:
  std::vector<std::shared_ptr<ShardctrlerIf> > ifaces_;
  ShardctrlerMultiface() {}
  void add(::std::shared_ptr<ShardctrlerIf> iface) {
    RaftMultiface::add(iface);
    ifaces_.push_back(iface);
  }
 public:
  void join(JoinReply& _return, const JoinArgs& jargs) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->join(_return, jargs);
    }
    ifaces_[i]->join(_return, jargs);
    return;
  }

  void leave(LeaveReply& _return, const LeaveArgs& largs) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->leave(_return, largs);
    }
    ifaces_[i]->leave(_return, largs);
    return;
  }

  void move(MoveReply& _return, const MoveArgs& margs) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->move(_return, margs);
    }
    ifaces_[i]->move(_return, margs);
    return;
  }

  void query(QueryReply& _return, const QueryArgs& qargs) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->query(_return, qargs);
    }
    ifaces_[i]->query(_return, qargs);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ShardctrlerConcurrentClient : virtual public ShardctrlerIf, public RaftConcurrentClient {
 public:
  ShardctrlerConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) :
    RaftConcurrentClient(prot, prot, sync) {}
  ShardctrlerConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) :    RaftConcurrentClient(iprot, oprot, sync) {}
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void join(JoinReply& _return, const JoinArgs& jargs) override;
  int32_t send_join(const JoinArgs& jargs);
  void recv_join(JoinReply& _return, const int32_t seqid);
  void leave(LeaveReply& _return, const LeaveArgs& largs) override;
  int32_t send_leave(const LeaveArgs& largs);
  void recv_leave(LeaveReply& _return, const int32_t seqid);
  void move(MoveReply& _return, const MoveArgs& margs) override;
  int32_t send_move(const MoveArgs& margs);
  void recv_move(MoveReply& _return, const int32_t seqid);
  void query(QueryReply& _return, const QueryArgs& qargs) override;
  int32_t send_query(const QueryArgs& qargs);
  void recv_query(QueryReply& _return, const int32_t seqid);
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
